### ISSUE TITLE
Building a Serverless Data Pipeline - memory leak? 

### ISSUE THREAD

**Issue by TechnologyColorado** [googlecodelabs/iot-data-pipeline#5]
The checkWeather.py script or one of the routines it calls seems to have a memory leak.  After a few hours the application abruptly terminates.  Syslog indicates it was killed because the pi ran out of memory resources.  The recommended Raspberry Pi Zero W was used for the lab with the following Raspbian version.  It was a fresh install of Raspbian and no steps were performed or applications loaded other than the steps in the lab.  I then tried reformatting the microSD card and reloading OS and apps again per the lab instructions, but same results.  I found that if I set the Pi to not load X using raspi-config this frees up additional memory and it takes longer before it runs out of memory, but it still runs out of memory after 12 hours or so.   

Raspbian Version
Version:April 2018
Release date:2018-04-18
Kernel version:4.14

**Comment by shraderdm** [comment]
I also had a similar issue. In my case, I found the error to be "Too many open files"

To get around this, my solution was to set a cron job for the Pi to reboot every two hours. This obviously doesn't fix the problem, but it works to avoid the crashes. Also, for this solution, you'll need to create a systemd unit file for the checkWeather.py script, and then enable it.

**Comment by sunsetmountain** [comment]
It appears that the Publisher object isn't being garbage collected appropriately. The code had a separate function that would create a Publisher, send the message off to PubSub and then return, but this ended up eating up a bit of memory every time it was called. Therefore, I merged the creation of the Publisher object into main so that it is only created once.
